# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(default='')),
                ('event_detail', models.TextField(default='')),
                ('event_numset', models.IntegerField(default=0)),
                ('event_location', models.TextField(default='')),
                ('pcount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(default='')),
                ('lname', models.TextField(default='')),
                ('event', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
